// src/lib/constants.js
export const AUTH = {
	BCRYPT_ROUNDS: 12,
	DEFAULT_PIN: '0000',
	MIN_PIN_LENGTH: 4,
	MAX_PIN_LENGTH: 20,
	PHONE_MIN_LENGTH: 8,
	PHONE_MAX_LENGTH: 15
};

export const PAGINATION = {
	DEFAULT_LIMIT: 10,
	MAX_LIMIT: 100
};

export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	INTERNAL_ERROR: 500
};
